### ISSUE TITLE
Broker do not push ack on passive host

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon-broker#191]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.26

**Centreon Engine version**:   centreon-engine-1.8.1-1.el7.centos.x86_64

**Centreon Broker version**:  centreon-broker-3.0.14-1.el7.centos.x86_64

**OS**:  CentOS 7

**Steps to reproduce the issue:**
1. Try to Ack a **passive** host (host without an active ping)

**Describe the results you received:**
The Ack is visible in Centengine through livestatus, but NOT in Centreon web UI.
You must stop/start Centengine to see the Ack in effect in Centreon web UI.

**Describe the results you expected:**
The Ack must be visible on the host, in the  Centreon web UI.

**Additional information you think important (e.g. issue happens only occasionally):**
Everytime on a passive host.

**Comment by omercier** [comment]
Hi,
This has been a long wait... I apologize.
I have tried to reproduce your issue on the last three major releases of Centreon but every time, the acknowledgement appeared in the Web UI.
How I tried it:
* created a host using the "generic-passive-host-custom" template
* set the DUMMYSTATUS macro to DOWN
* exported the configuration
* forced a check on the host to make its state change to DOWN (if state is pending or OK/UP, acknowledgements are ignored)
* acknowledged it
And the acknowledgement appeared in the Web UI.

I guess the issue has been fixed in the meantime...
Again, sorry for the long wait.
