### ISSUE TITLE
Only forward checks' results between brokers (no perfdata)

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-broker#318]
Hi,

I run a central server A, with broker sending perfdata to InfluxDB using stream-connector script.
As I don't even need graphs in Centreon web, I removed RRD output from broker configuration.
Perfect.

Now I've connected a remote server B to this central server A.
Broker B then sends its checks' results' and perfdata to broker A.
And broker A sends perfdata from broker B to InfluxDB.
Pretty simple, works flawlessly, perfect.

However, for various reasons, I would like broker B to send its perfdata to InfluxDB itself.
I just then have to configure the same stream-connector script on broker B.
Easy.
But how to ask broker B not to send its perfdata to broker A, but then only its checks' results ?

So that :
- perfdata from broker B is not inserted twice ;
- traffic from broker B to broker A is reduced, as only checks' results would be sent.

Thank you very much 👍 

Edit : still missing from 19.10.5.

**Comment by bouda1** [comment]
Hi @CPbN 
In the B broker output to A Broker, maybe you could add a filter allowing only neb events.
Or I missed something :-)

Cheers.

**Comment by CPbN** [comment]
Hi @bouda1, and thank you for your answer !

This is what is done by default :

![image](https://user-images.githubusercontent.com/40244829/67196546-53d01f00-f3fb-11e9-9520-1402ee3bc834.png)

But from what I experience, this does not prevent broker B from sending its perfdata to broker A :-)

**Comment by bouda1** [comment]
OK. This use case is not managed for now.

Each time a **neb** event arrives on the central broker, if the storage is enabled, it will get the perfdata from the **neb** to make metrics and status.

So in your case _Broker B_ produces its metrics and send them to _influxdb_ whereas _Broker A_ receives **neb** events, converts them also into metrics and send them to _influxdb_.

The only solution I can see is to add a filter on your central stream connector to avoid **neb** events from pollers with a given **instance_id**. The solution is not trivial since the **instance_id** is not part of **service_status** nor **host_status** events. You will have to also listen to **host** events that contain an **instance_id** and produce your own cache with those informations.

**Comment by CPbN** [comment]
Yep filtering events in central stream connector script could be a workaround.
But of course this perfdata from broker B to A will still lead to useless traffic, and additional load on broker A.

Do you then think it could be a good thing to add a broker option which would allow to forward metrics without perfdata ?

Many thx again 👍

**Comment by bouda1** [comment]
Yes, you are right. We could imagine something to forbid the metrics generation or something like this. Again, not so trivial but we talked about it here.

**Comment by UrBnW** [comment]
I simply close this, @Sims24 gave me a nice clue 👍
Trick is rather simple, instead of configuring the Stream Connector at the broker level, we should configure it at the module (engine / cbmod) level. I did not think about that...
There's then no risk for the perfdata to be inserted a second time by a broker in the path.
And each poller works on its own to send its data to its Stream Connector, independently.
Perfect !
Thank you again @Sims24 !
