### ISSUE TITLE
centreon-broker ralease 20.04

### ISSUE THREAD

**Issue by kevin06700** [centreon/centreon-broker#419]
Hi
After installing the release centreon 20.04, I have this error on service Broker-Retention :

UNKNOWN: '/etc/centreon-broker/central-rrd.xml': not a file or cannot be read - '/etc/centreon-broker//etc/centreon-broker/': not a file or cannot be read
--

In directory /etc/centreon-broker/ I don't have this file central-rrd.xml just the file central-rrd.xml rpmsave

Can you help me please ?

**Comment by Sims24** [comment]
Hi @kevin06700 

You must export your configuration file from Web UI. Broker config file a now .json.

**Comment by bouda1** [comment]
broke no more uses xml file for configuration. It nows uses json files.
If you have made an upgrade from a previous version, you already have a configuration in your database. So, you just have to generate the new configuration from the web interface:
![image](https://user-images.githubusercontent.com/6324413/81062416-31ed4400-8ed6-11ea-92a1-51449adc9990.png)

Another point to check. Always in the web interface, check that your broker configuration files are json files and not xml. I give you an example just below:
![image](https://user-images.githubusercontent.com/6324413/81062608-95777180-8ed6-11ea-89ae-f4143b077d98.png)

**Comment by kevin06700** [comment]
Thks for your feedback 

I did It but nothing change I have already this error central-rrd.xml ...

I can change this Broker-Retention command ?

**Comment by hecko** [comment]
This issue is still present.
Af of plugins release centreon-plugin-Applications-Monitoring-Centreon-Central-20220113-084434.el7.centos.noarch this check does not support JSON files, only XML so the check itself is not in sync with the configuration export file format for broker.

This needs to be fixed in https://github.com/centreon/centreon-plugins/blob/master/apps/centreon/local/mode/retentionbroker.pm i think @garnier-quentin

**Comment by bouda1** [comment]
I think this issue is fixed now.

Please, reopen it on centreon-collect repo if needed.
