### ISSUE TITLE
Fichier de retention

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-broker#74]
**Centreon WEB version**: 2.8.1
**Centreon Broker version**: 3.0.1
**Centreon Engine version**: 1.6.0

J'ai l'impression qu'il y a un problème sur les fichiers de retentions, lié au failover configuré sur la partie broker. 
Aucun fichier n'est créé, sauf "*.memory.*" et "*.queue.*". D'ailleurs je n'ai pas trouvé où est configurable le "path" de ces deux types de fichiers. 

Si je regarde bien le code source, ce path devrait être présent dans la configuration des brokers et je ne le trouve pas depuis l'interface WEB:  

./core/src/config/applier/state.cc

```
  // Set cache directory.
  _cache_dir = s.cache_directory();
  if (_cache_dir.empty())
    _cache_dir.append(PREFIX_VAR);
  _cache_dir.append("/");
  _cache_dir.append(s.broker_name());
```
------------------
Le problème de retention n'est pas présent avec la configuration ci-dessous: 
**Centreon WEB version**: 2.7.6
**Centreon Broker version**: 2.11.5
**Centreon Engine version**: 1.6.0

**Comment by romsworld** [comment]
Hello,

As tu trouvé une solution, je pense avoir le meme probleme.

Merci,

**Comment by ganoze** [comment]
Hi,

The path to the cache directory is not currently editable through Centreon Web. It must be properly configured when compiling Centreon Broker sources. This will be fixed in the upcoming 2.8.5 release of Centreon Web.

As to the retention file failovers, they should be created automatically by Centreon Web (2.8.4 or older). They will be placed in the *Retention path*. Again, this will be fixed in the next release of Centreon Web where *Retention path* will be dropped and replaced by the *Cache directory* configuration directive.
