### ISSUE TITLE
centreon-broker upgrade 2.11 to 3.0.2

### ISSUE THREAD

**Issue by snaki4** [centreon/centreon-broker#80]
Good afternoon,

Tried to upgrade centreon from 2.7 to 2.8 (broker and engine has been upgraded aswell) and got an issue that centreon-broker wont start.Errors like :

[1481840670] [0x138c090] info:    file: opening new file '/usr/var/central-broker-rrd-master.memory.central-broker-rrd-master-input'
[1481840670] [0x138c090] error:   cannot open '/usr/var/central-broker-rrd-master.memory.central-broker-rrd-master-input' (mode w+): No such file or directory

It does looks like that it misunderstand tcp/ipv4 input  configuration and tries to find some local file ... Is centreon 2.8 compatible with broker 3.2?

**Comment by sebastienmaury** [comment]
Hello,

In case it can help : #https://github.com/centreon/centreon-broker/issues/81

Regards,
Sébastien

**Comment by ganoze** [comment]
It seems that you compiled Centreon Broker yourself. This is caused by the missing WITH_PREFIX_VAR build option that generated the weird /usr/var path.

I've added two commits that will fix your problem.

7daf70e128a3f62ef9df55865d3e3edec161b957 to document the WITH_PREFIX_VAR build option and abd0edfac456556e61289120e5f3afd3db7de8ba to install and chown the forementioned directory.
